http:
  port: 10000
https:
  port: 11111
#   host: https://onlxam.herokuapp.com
apiEndpoints:
  auth:
    host: onlxam.herokuapp.com
    paths: 
      - '/api/auth/*'
      - '/api/profile/'
      - '/api/profile/*'
  exam:
#     host: https://onlxam.herokuapp.com
    paths: 
      - '/api/exams/'
      - '/api/exams/*'
      - '/api/results/'
      - '/api/results/*'
  question:
#     host: https://onlxam.herokuapp.com
    paths: 
      - '/api/libraries/'
      - '/api/libraries/*'
      - '/api/questions/'
      - '/api/questions/*'
  user:
#     host: https://onlxam.herokuapp.com
    paths: 
      - '/api/classes/'
      - '/api/classes/*'
      - '/api/users/'
      - '/api/users/*'
serviceEndpoints:
  auth-url:
    url: 'https://onlxam-a.herokuapp.com/'  
  exam-url:
    url: 'https://onlxam-e.herokuapp.com/'
  question-url:
    url: 'https://onlxam-q.herokuapp.com/'  
  user-url:
    url: 'https://onlxam-u.herokuapp.com/'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  auth-service:
    apiEndpoints:
      - auth
    policies:
      - proxy:
          - action:
              serviceEndpoint: auth-url 
              changeOrigin: true
  exam-service:
    apiEndpoints:
      - exam
    policies:
      - proxy:
          - action:
              serviceEndpoint: exam-url 
              changeOrigin: true
  question-service:
    apiEndpoints:
      - question
    policies:
      - proxy:
          - action:
              serviceEndpoint: question-url 
              changeOrigin: true
  user-service:
    apiEndpoints:
      - user
    policies:
      - proxy:
          - action:
              serviceEndpoint: user-url 
              changeOrigin: true
